services:
  docmost:
    build: .
    depends_on:
      - db
      - redis
    environment:
      APP_URL: 'http://localhost:3000'
      APP_SECRET: 'docmost-secret-key-for-development-2024'
      DATABASE_URL: 'postgresql://docmost:STRONG_DB_PASSWORD@db:5432/docmost'
      REDIS_URL: 'redis://redis:6379'
    ports:
      - "3000:3000"
    restart: unless-stopped
    volumes:
      - docmost:/app/data/storage

  casdoor:
    image: casbin/casdoor:latest
    depends_on:
      - db
    environment:
      driverName: postgres
      dataSourceName: "host=db port=5432 user=docmost password=STRONG_DB_PASSWORD dbname=casdoor sslmode=disable"
      origin: 'http://localhost:8000'
      staticBaseUrl: 'https://cdn.jsdelivr.net/gh/casbin/static-resources@latest'
    ports:
      - "8000:8000"
    restart: unless-stopped

  db:
    image: pgvector/pgvector:pg18
    environment:
      POSTGRES_DB: docmost
      POSTGRES_USER: docmost
      POSTGRES_PASSWORD: STRONG_DB_PASSWORD
    ports:
      - "5432:5432"
    restart: unless-stopped
    volumes:
      - db_data:/var/lib/postgresql
      - ./docker-init/init-casdoor-db.sql:/docker-entrypoint-initdb.d/init-casdoor-db.sql
      - ./docker-init/init-pgvector.sql:/docker-entrypoint-initdb.d/init-pgvector.sql

  redis:
    image: redis:8
    command: ["redis-server", "--appendonly", "yes", "--maxmemory-policy", "noeviction"]
    ports:
      - "6379:6379"
    restart: unless-stopped
    volumes:
      - redis_data:/data

volumes:
  docmost:
  db_data:
  redis_data:
