import { AiAction } from "@/ee/ai/types/ai.types.ts";
import {
  IconSparkles,
  IconArrowsMaximize,
  IconArrowsMinimize,
  IconWriting,
  IconHelp,
  IconList,
  IconMoodSmile,
  IconLanguage,
  IconTrash,
  IconRefresh,
  IconChevronLeft,
  IconCheck,
  IconArrowDownLeft,
  IconCopy,
  IconTextPlus,
  IconAlignJustified,
  IconMessage,
} from "@tabler/icons-react";

interface CommandItem {
  name: string;
  translationKey: string;
  id: string;
  icon?: typeof IconSparkles;
  action?: AiAction;
  prompt?: string;
  subCommandSet?: CommandSet;
}

type CommandSet = "main" | "tone" | "translate" | "result";

const mainItems: CommandItem[] = [
  {
    id: "improve-writing",
    name: "Improve writing",
    translationKey: "ai.improve_writing",
    icon: IconSparkles,
    action: AiAction.IMPROVE_WRITING,
  },
  {
    id: "fix-spelling-grammar",
    name: "Fix spelling & grammar",
    translationKey: "ai.fix_spelling",
    icon: IconCheck,
    action: AiAction.FIX_SPELLING_GRAMMAR,
  },
  {
    id: "make-longer",
    name: "Make longer",
    translationKey: "ai.make_longer",
    icon: IconTextPlus,
    action: AiAction.MAKE_LONGER,
  },
  {
    id: "make-shorter",
    name: "Make shorter",
    translationKey: "ai.make_shorter",
    icon: IconAlignJustified,
    action: AiAction.MAKE_SHORTER,
  },
  {
    id: "continue-writing",
    name: "Continue writing",
    translationKey: "ai.continue_writing",
    icon: IconWriting,
    action: AiAction.CONTINUE_WRITING,
  },
  {
    id: "explain",
    name: "Explain",
    translationKey: "ai.explain",
    icon: IconHelp,
    action: AiAction.EXPLAIN,
  },
  {
    id: "summarize",
    name: "Summarize",
    translationKey: "ai.summarize",
    icon: IconList,
    action: AiAction.SUMMARIZE,
  },
  {
    id: "change-tone",
    name: "Change tone",
    translationKey: "ai.change_tone",
    icon: IconMoodSmile,
    subCommandSet: "tone",
  },
  {
    id: "translate",
    name: "Translate",
    translationKey: "ai.translate",
    icon: IconLanguage,
    subCommandSet: "translate",
  },
];
const toneItems: CommandItem[] = [
  {
    id: "back",
    name: "Back",
    translationKey: "ai.back",
    icon: IconChevronLeft,
  },
  {
    id: "tone-professional",
    name: "Professional",
    translationKey: "ai.tone_professional",
    icon: IconMoodSmile,
    action: AiAction.CHANGE_TONE,
    prompt: "Professional",
  },
  {
    id: "tone-casual",
    name: "Casual",
    translationKey: "ai.tone_casual",
    icon: IconMoodSmile,
    action: AiAction.CHANGE_TONE,
    prompt: "Casual",
  },
  {
    id: "tone-friendly",
    name: "Friendly",
    translationKey: "ai.tone_friendly",
    icon: IconMoodSmile,
    action: AiAction.CHANGE_TONE,
    prompt: "Friendly",
  },
  {
    id: "tone-academic",
    name: "Academic",
    translationKey: "ai.tone_academic",
    icon: IconMoodSmile,
    action: AiAction.CHANGE_TONE,
    prompt: "Academic",
  },
  {
    id: "tone-formal",
    name: "Formal",
    translationKey: "ai.tone_formal",
    icon: IconMoodSmile,
    action: AiAction.CHANGE_TONE,
    prompt: "Formal",
  },
  {
    id: "tone-empathetic",
    name: "Empathetic",
    translationKey: "ai.tone_empathetic",
    icon: IconMoodSmile,
    action: AiAction.CHANGE_TONE,
    prompt: "Empathetic",
  },
  {
    id: "tone-urgent",
    name: "Urgent",
    translationKey: "ai.tone_urgent",
    icon: IconMoodSmile,
    action: AiAction.CHANGE_TONE,
    prompt: "Urgent",
  },
];
const translateItems: CommandItem[] = [
  {
    id: "back",
    name: "Back",
    translationKey: "ai.back",
    icon: IconChevronLeft,
  },
  {
    id: "translate-english",
    name: "English",
    translationKey: "ai.lang_english",
    icon: IconLanguage,
    action: AiAction.TRANSLATE,
    prompt: "English",
  },
  {
    id: "translate-chinese",
    name: "Chinese (Simplified)",
    translationKey: "ai.lang_chinese",
    icon: IconLanguage,
    action: AiAction.TRANSLATE,
    prompt: "Simplified Chinese",
  },
  {
    id: "translate-spanish",
    name: "Spanish",
    translationKey: "ai.lang_spanish",
    icon: IconLanguage,
    action: AiAction.TRANSLATE,
    prompt: "Spanish",
  },
  {
    id: "translate-french",
    name: "French",
    translationKey: "ai.lang_french",
    icon: IconLanguage,
    action: AiAction.TRANSLATE,
    prompt: "French",
  },
  {
    id: "translate-german",
    name: "German",
    translationKey: "ai.lang_german",
    icon: IconLanguage,
    action: AiAction.TRANSLATE,
    prompt: "German",
  },
  {
    id: "translate-japanese",
    name: "Japanese",
    translationKey: "ai.lang_japanese",
    icon: IconLanguage,
    action: AiAction.TRANSLATE,
    prompt: "Japanese",
  },
  {
    id: "translate-korean",
    name: "Korean",
    translationKey: "ai.lang_korean",
    icon: IconLanguage,
    action: AiAction.TRANSLATE,
    prompt: "Korean",
  },
  {
    id: "translate-russian",
    name: "Russian",
    translationKey: "ai.lang_russian",
    icon: IconLanguage,
    action: AiAction.TRANSLATE,
    prompt: "Russian",
  },
  {
    id: "translate-arabic",
    name: "Arabic",
    translationKey: "ai.lang_arabic",
    icon: IconLanguage,
    action: AiAction.TRANSLATE,
    prompt: "Arabic",
  },
  {
    id: "translate-portuguese",
    name: "Portuguese",
    translationKey: "ai.lang_portuguese",
    icon: IconLanguage,
    action: AiAction.TRANSLATE,
    prompt: "Portuguese",
  },
  {
    id: "translate-italian",
    name: "Italian",
    translationKey: "ai.lang_italian",
    icon: IconLanguage,
    action: AiAction.TRANSLATE,
    prompt: "Italian",
  },
  {
    id: "translate-dutch",
    name: "Dutch",
    translationKey: "ai.lang_dutch",
    icon: IconLanguage,
    action: AiAction.TRANSLATE,
    prompt: "Dutch",
  },
  {
    id: "translate-turkish",
    name: "Turkish",
    translationKey: "ai.lang_turkish",
    icon: IconLanguage,
    action: AiAction.TRANSLATE,
    prompt: "Turkish",
  },
  {
    id: "translate-vietnamese",
    name: "Vietnamese",
    translationKey: "ai.lang_vietnamese",
    icon: IconLanguage,
    action: AiAction.TRANSLATE,
    prompt: "Vietnamese",
  },
  {
    id: "translate-thai",
    name: "Thai",
    translationKey: "ai.lang_thai",
    icon: IconLanguage,
    action: AiAction.TRANSLATE,
    prompt: "Thai",
  },
  {
    id: "translate-polish",
    name: "Polish",
    translationKey: "ai.lang_polish",
    icon: IconLanguage,
    action: AiAction.TRANSLATE,
    prompt: "Polish",
  },
  {
    id: "translate-hindi",
    name: "Hindi",
    translationKey: "ai.lang_hindi",
    icon: IconLanguage,
    action: AiAction.TRANSLATE,
    prompt: "Hindi",
  },
  {
    id: "translate-swedish",
    name: "Swedish",
    translationKey: "ai.lang_swedish",
    icon: IconLanguage,
    action: AiAction.TRANSLATE,
    prompt: "Swedish",
  },
];
const resultItems: CommandItem[] = [
  { id: "result-replace", name: "Replace", translationKey: "ai.result_replace", icon: IconCheck },
  { id: "result-insert-below", name: "Insert below", translationKey: "ai.result_insert_below", icon: IconArrowDownLeft },
  { id: "result-copy", name: "Copy", translationKey: "ai.result_copy", icon: IconCopy },
  { id: "result-discard", name: "Discard", translationKey: "ai.result_discard", icon: IconTrash },
  {
    id: "result-try-again",
    name: "Try again",
    translationKey: "ai.result_try_again",
    icon: IconRefresh,
  },
  {
    id: "result-continue-in-chat",
    name: "Continue in chat",
    translationKey: "ai.result_continue_in_chat",
    icon: IconMessage,
  },
];
const commandItems: Record<CommandSet, CommandItem[]> = {
  main: mainItems,
  tone: toneItems,
  translate: translateItems,
  result: resultItems,
};

export type { CommandItem, CommandSet };
export { commandItems };
